logging:
  version: 1
  formatters:
    brief:
      format: '%(message)s'
    default:
      format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
      datefmt: '%Y-%m-%d %H:%M:%S'
  handlers:
    console:
      level: INFO
      class: logging.StreamHandler
      stream: ext://sys.stderr
      formatter: brief
    file:
      level: INFO
      class: logging.handlers.RotatingFileHandler
      formatter: default
      filename: application.log
      maxBytes: 1048578 # 1 MiB
  loggers:
    '': # root logger
      level: INFO
      handlers:
        - console
        - file
